# Kandungan slaid Hari 1. Sunting di sini, kemudian jalankan: python3 slaid/bina.py
# Jenis slaid: title, section, big, quote, points, cards, flow, table, agenda, act,
# compare, lights, quiz, anatomy, email, case, close, memo.
# <em>perkataan</em> = penekanan italik berwarna. Semua contoh menggunakan data rekaan.

PENCERAMAH = "PM Dr Mohd Murtadha Mohamad"

# ------------------------------------------------------------------ MODUL 1
M1 = dict(
    file="modul-1.html", label="Modul 1 &middot; Asas AI",
    title="Modul 1: Asas AI dan Generative AI",
    desc="Slaid Modul 1: pengenalan AI dan AI generatif, peta alat, keselamatan data, aktiviti Gemini.",
    slides=[
        dict(t="title", giant="01", eyebrow="Modul 1 &middot; Kursus Aplikasi AI dalam Tugas Rasmi",
             h="Asas <em>AI</em> dan Generative AI", image="img/pejabat-ai.jpg",
             image_alt="Ilustrasi pegawai kejuruteraan Malaysia menyemak pelan jalan di pejabat dengan bantuan AI.",
             sub="Apa itu AI generatif, apa ia boleh dan tidak boleh buat, dan cara menggunakannya dengan selamat.",
             pills=["8.30-9.30 pagi", "60 minit", PENCERAMAH],
             notes="Selamat datang. Pastikan semua sudah menjawab Pra-Ujian dan sudah log masuk ke komputer makmal."),
        dict(t="points", kicker="Hasil pembelajaran", h="Selepas 60 minit, anda <em>boleh</em>:",
             items=[("Menerangkan AI generatif dalam ayat sendiri", "Tanpa istilah teknikal, kepada rakan sepejabat."),
                    ("Menjana kandungan pertama dalam Gemini", "Teks, imej dan muzik menggunakan akaun jabatan."),
                    ("Membezakan data yang boleh dan tidak boleh dimasukkan", "Menggunakan lampu isyarat Hijau, Kuning, Merah.")],
             notes="Tiga hasil ini akan diuji semula dalam Pasca-Ujian."),
        dict(t="agenda", kicker="Aliran modul", h="Ceramah dan cubaan <em>selang-seli</em>",
             rows=[("8.30", "1.1", "Pembuka: pejabat masa depan dalam satu prompt", "Demo"),
                   ("8.40", "CS1", "Log masuk dan prompt pertama", "Cuba Sekarang"),
                   ("8.50", "1.3", "Apa itu AI? Peta alat dan contoh JKR", "Ceramah"),
                   ("9.05", "CS2", "Poster keselamatan tapak", "Cuba Sekarang"),
                   ("9.15", "1.5", "Keselamatan data dan kuiz CS3", "Ceramah"),
                   ("9.25", "CS4", "Jingle kumpulan 30 saat", "Cuba Sekarang")],
             notes="Kod CS merujuk aktiviti dalam Bank Prompt di laman kursus."),
        dict(t="section", giant="1.1", eyebrow="Demo pembuka", h="Pejabat masa depan dalam <em>satu prompt</em>", image="img/pejabat-ai.jpg",
             image_alt="Ilustrasi pegawai kejuruteraan Malaysia menyemak pelan jalan di pejabat dengan bantuan AI.",
             sub="Penceramah menjana imej pejabat JKR masa depan secara langsung.",
             notes="Jana imej secara langsung. Tanya: berapa lama kerja ini jika diupah kepada pereka? Kemudian zum pada tulisan dan logo yang salah."),
        dict(t="cards", kicker="Perhatikan hasil demo", h="Pantas dan menarik, tetapi <em>tidak sempurna</em>", cols=3,
             cards=[dict(icon="clock", lab="Masa", h="Beberapa saat", p="Kerja yang biasanya mengambil berjam-jam disiapkan sebagai draf pertama."),
                    dict(icon="alert", lab="Kesilapan", h="Tulisan dan logo", p="AI kerap tersilap ejaan, logo dan butiran kecil yang penting."),
                    dict(icon="user", lab="Peranan anda", h="Semak dan putuskan", p="Manusia menilai, membetulkan dan bertanggungjawab ke atas hasil.", hl=True)],
             notes="Gunakan kesilapan dalam imej demo sebagai bukti mengapa semakan manusia wajib."),
        dict(t="guess", kicker="1.1 &middot; Teka", h="Yang mana <em>foto asli</em>?", menu="Teka: foto asli atau AI?",
             sub="Tiga potret penceramah. Undi A, B atau C sebelum jawapan didedahkan.",
             items=[("A", "img/foto-a.jpg", "AI", "Gemini Thinking"),
                    ("B", "img/foto-b.jpg", "AI", "Gemini Flash"),
                    ("C", "img/foto-c.jpg", "AI", "Gemini Pro")],
             notes="Minta peserta angkat tangan untuk A, B atau C. Kemudian klik setiap foto. Jawapan: ketiga-tiganya dijana AI daripada prompt yang sama pada tiga model Gemini."),
        dict(t="points", kicker="Jawapan", h="Ketiga-tiganya <em>dijana AI</em>", menu="Jawapan: ketiga-tiganya AI",
             items=[("Satu prompt, tiga model, tiga potret", "Gemini Thinking, Flash dan Pro; tiada satu pun foto sebenar."),
                    ("Mata kasar tidak lagi cukup", "Petanda lama seperti jari, teks dan latar pelik semakin sukar dikesan."),
                    ("Foto bukan bukti dengan sendirinya", "Untuk aduan, laporan tapak atau tuntutan, sahkan sumber, tarikh dan pengambil gambar."),
                    ("Kandungan AI perlu dilabel", "Imej Google membawa tera air digital SynthID yang tidak kelihatan.")],
             notes="Jika masa mengizinkan, tunjukkan cara bertanya Gemini sama ada imej dijana oleh AI Google (semakan SynthID). Sahkan ciri ini tersedia dalam akaun jabatan sebelum demo."),
        dict(t="big", kicker="Prinsip hari ini", h="AI <em>mencadang</em>.<br>Manusia memutuskan.", image="img/manusia-ai.jpg",
             image_alt="Ilustrasi jurutera menyemak laporan yang dicadangkan pembantu AI.",
             sub="Setiap aktiviti hari ini berakhir dengan semakan oleh anda.",
             notes="Ulang prinsip ini pada setiap peralihan modul."),
        dict(t="act", h="Log masuk dan prompt pertama", min=8, menu="CS1: Prompt pertama",
             sub="Buka gemini.google.com dan log masuk dengan akaun jabatan.",
             steps=["Buka <b>gemini.google.com</b>.", "Log masuk dengan akaun jabatan.", "Salin prompt, ganti [jawatan], tekan Enter.", "Gagal log masuk? Guna aplikasi Gemini di telefon."],
             prompt=("CS1 &middot; Prompt pertama",
                     "Saya [jawatan] di JKR Daerah. Senaraikan 5 tugas harian saya yang boleh dipercepat dengan AI, dan untuk setiap satu beri satu contoh arahan ringkas. Jawab dalam Bahasa Melayu, dalam bentuk jadual."),
             follow=[("Bincang", "Tugas mana dalam jadual itu yang benar-benar anda lakukan setiap minggu?")],
             notes="Fasilitator bergerak membantu log masuk. Minta dua peserta berkongsi jadual mereka."),
        dict(t="section", giant="1.3", eyebrow="Ceramah", h="Apa itu <em>AI</em>?", image="img/manusia-ai.jpg",
             image_alt="Ilustrasi jurutera menyemak laporan yang dicadangkan pembantu AI.", sub="Definisi, analogi, tiga pendekatan dan peta alat.",
             notes="Peralihan ke bahagian konsep, kira-kira 15 minit."),
        dict(t="quote", kicker="Definisi kerja", h="AI ialah pembantu digital yang menghasilkan cadangan berdasarkan arahan kita.", image="img/manusia-ai.jpg",
             image_alt="Ilustrasi jurutera menyemak laporan yang dicadangkan pembantu AI.",
             src="Sumber: AI untuk Semua, drshahizan.github.io/ai-semua",
             notes="Tekankan perkataan cadangan. Ia tidak sentiasa betul dan tidak menggantikan pertimbangan manusia."),
        dict(t="cards", kicker="Analogi", h="Pembantu baharu yang <em>sangat rajin</em>", image="img/manusia-ai.jpg",
             image_alt="Ilustrasi jurutera menyemak laporan yang dicadangkan pembantu AI.", cols=3,
             cards=[dict(icon="check", bigicon=True, h="Telah membaca banyak", p="Pantas menulis, meringkas, menyusun dan menterjemah."),
                    dict(icon="map", bigicon=True, h="Tidak pernah ke tapak", p="Tidak kenal kontraktor, jalan atau prosedur jabatan kita."),
                    dict(icon="alert", bigicon=True, h="Kadang-kadang mereka-reka", p="Memberi jawapan salah dengan nada yang sangat yakin.")],
             notes="Analogi ini membantu peserta bukan teknikal memahami had AI tanpa istilah."),
        dict(t="cards", kicker="Tiga pendekatan teknologi", h="Tidak semua AI adalah <em>AI generatif</em>", cols=3,
             cards=[dict(icon="list", lab="01", h="Automasi peraturan", p="Ikut syarat tetap. Contoh: e-mel peringatan automatik."),
                    dict(icon="trend", lab="02", h="Pembelajaran mesin", p="Belajar corak daripada data. Contoh: ramalan kerosakan."),
                    dict(icon="spark", lab="03", h="AI generatif", p="Menjana kandungan baharu: teks, imej, video, muzik.", hl=True)],
             notes="Hari ini kita fokus pada pendekatan ketiga."),
        dict(t="cards", kicker="Apa yang akan kita jana hari ini", h="Satu alat, <em>lima jenis</em> hasil", cols=5,
             cards=[dict(icon="text", bigicon=True, h="Teks", p="Surat, e-mel, laporan, minit"),
                    dict(icon="image", bigicon=True, h="Imej", p="Poster, infografik"),
                    dict(icon="music", bigicon=True, h="Muzik", p="Jingle kumpulan"),
                    dict(icon="video", bigicon=True, h="Video", p="Klip 8 saat"),
                    dict(icon="eye", bigicon=True, h="Gambar", p="Huraian daripada foto tapak")],
             notes="Setiap jenis ada aktiviti Cuba Sekarang sendiri sepanjang hari."),
        dict(t="table", kicker="Peta alat AI", h="Gemini alat utama; yang lain untuk <em>perbandingan</em>",
             head=["Alat", "Pembuat", "Kegunaan utama", "Hari ini"],
             rows=[["Gemini", "Google", "Sembang, tulisan, imej, video, muzik, analisis gambar, Gems", "Alat utama"],
                   ["NotebookLM", "Google", "Bertanya kepada dokumen sendiri, ringkasan berasaskan sumber", "Disebut"],
                   ["Google Vids", "Google", "Video penerangan daripada skrip", "Demo"],
                   ["ChatGPT", "OpenAI", "Sembang dan tulisan umum", "Perbandingan"],
                   ["Copilot", "Microsoft", "Bantuan dalam Word, Excel, Outlook", "Perbandingan"],
                   ["Canva AI", "Canva", "Reka bentuk poster dan slaid", "Perbandingan"]],
             notes="Formula prompt yang sama berfungsi dalam semua alat ini. Ciri dan kuota berubah dari semasa ke semasa."),
        dict(t="cards", kicker="Contoh dalam JKR", h="Setiap jawatan ada <em>kegunaan</em> sendiri", image="img/tapak-selamat.jpg",
             image_alt="Ilustrasi jurutera menyemak tablet di kawasan kerja jalan yang dilindungi penghadang.", cols=4,
             cards=[dict(icon="hat", bigicon=True, h="Jurutera", p="Ringkasan laporan perunding, kertas taklimat."),
                    dict(icon="map", bigicon=True, h="Penolong Jurutera", p="Laporan lawatan tapak, surat kepada kontraktor."),
                    dict(icon="mail", bigicon=True, h="Pembantu Tadbir", p="Surat rasmi, e-mel, minit mesyuarat, hebahan."),
                    dict(icon="cone", bigicon=True, h="Pembantu Kemahiran", p="Laporan kerja harian, senarai semak keselamatan.")],
             notes="Tanya peserta jawatan mereka, dan minta mereka pilih satu kegunaan untuk dicuba minggu depan."),
        dict(t="act", h="Poster keselamatan tapak", min=10, menu="CS2: Poster keselamatan",
             sub="Imej AI boleh diperbetul melalui perbualan.",
             steps=["Salin prompt ke Gemini.", "Semak tulisan pada poster.", "Hantar prompt susulan untuk ubah satu perkara."],
             prompt=("CS2 &middot; Imej",
                     'Jana poster menegak gaya ilustrasi rata: pekerja jalan raya Malaysia memakai topi keselamatan, jaket pemantul cahaya dan kasut keselamatan di tapak penurapan. Tajuk besar: "PAKAI PPE, PULANG SELAMAT". Warna kuning dan biru tua.'),
             follow=[("Susulan", "<code>Tukar latar kepada waktu malam dengan lampu amaran, kekalkan tajuk.</code>")],
             notes="Minta peserta kira berapa perkataan yang salah eja pada poster mereka."),
        dict(t="section", giant="1.5", eyebrow="Ceramah + kuiz", h="Keselamatan <em>data</em>", image="img/data-selamat.jpg",
             image_alt="Ilustrasi fail sulit dilindungi kunci dan perisai sebelum menggunakan AI.", sub="Apa yang boleh, perlu dilindungi, dan tidak boleh dimasukkan ke dalam AI.",
             notes="Bahagian paling penting dari segi pematuhan."),
        dict(t="lights", kicker="Lampu isyarat data", h="Sebelum menampal, <em>tanya</em> warna apa?",
             items=[("g", "Hijau: boleh", "Maklumat awam, data rekaan, templat kosong, teks yang telah dibuang nama."),
                    ("y", "Kuning: lindungi dahulu", "Dokumen dalaman. Buang nama, nombor telefon, alamat dan nombor rujukan sebelum menampal."),
                    ("r", "Merah: jangan", "Dokumen terperingkat, nombor IC, akaun bank, kata laluan, maklumat peribadi orang awam.")],
             notes="Rujuk juga pekeliling dan dasar keselamatan maklumat jabatan anda yang terkini."),
        dict(t="quiz", kicker="CS3 &middot; Kuiz", h="Boleh atau <em>tidak</em>?", menu="CS3: Kuiz boleh atau tidak",
             items=[("Muat naik senarai nama penduduk terjejas supaya AI menulis surat kepada setiap seorang.", "r", "Maklumat peribadi orang awam."),
                    ("Minta AI meringkaskan garis panduan yang telah diterbitkan di laman web rasmi.", "g", "Maklumat awam."),
                    ("Tampal draf laporan dalaman selepas membuang nama kontraktor dan nombor rujukan.", "y", "Dalaman, tetapi telah dilindungi."),
                    ("Tampal nombor IC dan akaun bank kontraktor untuk menyemak borang bayaran.", "r", "Data peribadi dan kewangan."),
                    ("Jana poster keselamatan menggunakan nama tapak dan pekerja rekaan.", "g", "Data rekaan."),
                    ("Tampal nota mesyuarat dalaman yang masih mengandungi nama pegawai dan nombor telefon.", "y", "Buang nama dan nombor dahulu.")],
             notes="Baca setiap senario. Peserta angkat kad atau tangan hijau, kuning atau merah. Klik kad untuk dedah jawapan."),
        dict(t="points", kicker="Had AI", h="Tiga perkara yang <em>mesti</em> diingat", style="warn",
             items=[("Halusinasi", "AI boleh mencipta nombor rujukan, nama akta atau angka yang kelihatan meyakinkan. Semak setiap fakta."),
                    ("AI ialah pembantu, bukan pegawai pelulus", "Tanggungjawab tidak boleh diserahkan kepada AI."),
                    ("Label kandungan AI untuk orang awam", "Ikut amalan jabatan. Imej dan video Google membawa tera air digital yang tidak kelihatan.")],
             notes="Contoh halusinasi: minta AI menyebut nombor pekeliling tertentu dan lihat ia mereka-reka."),
        dict(t="act", h="Jingle kumpulan 30 saat", min=8, menu="CS4: Jingle kumpulan",
             sub="Satu jingle setiap kumpulan, menggunakan menu Buat muzik dalam Gemini.",
             steps=["Pilih menu <b>Buat muzik</b> dalam Gemini.", "Ganti [nama kumpulan].", "Simpan pautan jingle untuk diundi selepas makan tengah hari."],
             prompt=("CS4 &middot; Muzik",
                     "Cipta jingle 30 saat, gaya pop Melayu ceria dengan kompang dan gitar, untuk pasukan penyelenggaraan jalan JKR. Lirik ringkas tentang kerja berpasukan dan jalan selamat untuk rakyat. Nama kumpulan: [nama kumpulan]."),
             follow=[("Jika lirik tidak jelas", "Tambah <code>instrumental sahaja</code>.")],
             notes="Jingle dimainkan selepas makan tengah hari dan diundi. Ini mengekalkan tenaga untuk sesi petang."),
        dict(t="close", kicker="Rumusan Modul 1", h="Bawa pulang <em>tiga</em> perkara",
             items=[("1", "AI mencadang", "Draf pertama dalam saat, tetapi tetap draf."),
                    ("2", "Manusia memutuskan", "Semak fakta, ejaan dan nada sebelum guna."),
                    ("3", "Lampu isyarat", "Hijau boleh, Kuning lindungi, Merah jangan.")],
             next=("Seterusnya: <b>Modul 2, Seni Membina Prompt</b> &middot; 9.30 pagi", "modul-2.html", "Slaid Modul 2"),
             notes="Tanya satu soalan semakan pantas sebelum beralih ke Modul 2."),
    ])

# ------------------------------------------------------------------ MODUL 2
M2 = dict(
    file="modul-2.html", label="Modul 2 &middot; Seni Membina Prompt",
    title="Modul 2: Seni Membina Prompt",
    desc="Slaid Modul 2: formula prompt Siapa + Apa + Cara, lima unsur, teknik prompt dan aktiviti sebelum-selepas.",
    slides=[
        dict(t="title", giant="02", eyebrow="Modul 2 &middot; Kursus Aplikasi AI dalam Tugas Rasmi",
             h="Seni Membina <em>Prompt</em>", image="img/m2-01-seni-membina-prompt.jpg",
             image_alt="Pegawai menyusun kad arahan untuk menghasilkan draf dengan bantuan AI.",
             sub="Daripada arahan kabur kepada arahan yang menghasilkan draf boleh guna.",
             pills=["9.30-10.30 pagi", "60 minit", PENCERAMAH]),
        dict(t="points", kicker="Hasil pembelajaran", h="Selepas 60 minit, anda <em>boleh</em>:",
             items=[("Menulis prompt lima unsur untuk teks", "Peranan, Konteks, Tugasan, Output, Kekangan."),
                    ("Menggunakan formula yang sama untuk imej", "Infografik dan poster."),
                    ("Memperbaiki output melalui prompt susulan", "Pendekkan, formalkan, jadikan jadual, terjemah.")]),
        dict(t="agenda", kicker="Aliran modul", h="Dari kabur kepada <em>jelas</em>",
             rows=[("9.30", "2.1", "Demo: \"Buatkan surat.\"", "Demo"),
                   ("9.35", "2.2", "Formula dalam dua tahap", "Ceramah"),
                   ("9.50", "CS5", "Sebelum dan selepas", "Cuba Sekarang"),
                   ("10.00", "2.4", "Empat teknik dan kesilapan biasa", "Ceramah"),
                   ("10.10", "CS6", "Formula yang sama untuk imej", "Cuba Sekarang")]),
        dict(t="big", kicker="2.1 &middot; Demo", h="&ldquo;Buatkan <em>surat</em>.&rdquo;", image="img/m2-04-arahan-kabur.jpg",
             image_alt="Arahan kabur menyebabkan pembantu AI meneka antara surat, e-mel dan laporan.",
             sub="Taip dua perkataan ini dalam Gemini. Apa yang anda dapat?",
             notes="Jalankan prompt ini secara langsung. Hasilnya surat umum yang tidak boleh digunakan."),
        dict(t="cards", kicker="Apa yang AI tidak tahu?", h="Prompt kabur, <em>output umum</em>", cols=5,
             cards=[dict(icon="user", bigicon=True, h="Kepada siapa?", p="Ketua Kampung, kontraktor, Pengarah?"),
                    dict(icon="q", bigicon=True, h="Tentang apa?", p="Penutupan jalan, mesyuarat, aduan?"),
                    dict(icon="chat", bigicon=True, h="Nada?", p="Rasmi, mesra, tegas?"),
                    dict(icon="text", bigicon=True, h="Format?", p="Surat rasmi, e-mel, jadual?"),
                    dict(icon="list", bigicon=True, h="Panjang?", p="Satu perenggan atau satu halaman?")],
             notes="Minta peserta menjawab lima soalan ini sebelum menulis prompt."),
        dict(t="cards", kicker="2.2 &middot; Formula tahap 1", h="Tiga soalan asas: <em>Siapa, Apa, Cara</em>", image="img/m2-06-siapa-apa-cara.jpg",
             image_alt="Tiga kumpulan objek mewakili peranan, konteks dan tugasan, serta output dan kekangan.", image_fit="contain", cols=3,
             cards=[dict(lab="Siapa", icon="user", h="Peranan", p="AI berlakon sebagai siapa?"),
                    dict(lab="Apa", icon="target", h="Konteks + Tugasan", p="Latar belakang apa, dan apa yang perlu dihasilkan?"),
                    dict(lab="Cara", icon="list", h="Output + Kekangan", p="Dalam bentuk apa, dan apa yang tidak boleh?", hl=True)],
             notes="Tahap 1 mudah diingat. Tahap 2 memecahkannya kepada lima unsur."),
        dict(t="table", kicker="Formula tahap 2", h="Lima unsur prompt", menu="Lima unsur prompt",
             head=["Asas", "Unsur", "Soalan", "Contoh JKR"],
             rows=[["Siapa", "Peranan", "AI berlakon sebagai siapa?", "Anda pembantu tadbir JKR Daerah"],
                   ["Apa", "Konteks", "Apa yang AI perlu tahu?", "Menurap semula Jalan Kg. Contoh, 14-16 Okt, 8 pagi hingga 5 petang"],
                   ["Apa", "Tugasan", "Apa yang perlu dihasilkan?", "Tulis surat makluman kepada Ketua Kampung"],
                   ["Cara", "Output", "Dalam bentuk apa?", "Format surat rasmi, maksimum 1 halaman"],
                   ["Cara", "Kekangan (pilihan)", "Apa yang tidak boleh?", "Jangan reka nombor rujukan; tinggalkan [ ]"]],
             notes="Kekangan ialah unsur paling kerap dilupakan, tetapi paling penting untuk mengelak halusinasi."),
        dict(t="act", badge="Struktur ringkas", h="Satu ayat, <em>lima</em> unsur", menu="Struktur ringkas",
             sub="Hafal templat ini. Ia berfungsi untuk surat, e-mel, laporan, imej dan video.",
             prompt=("Templat prompt",
                     "Anda [peranan].\n[Konteks].\nTugasan anda: [tugasan].\nHasilkan dalam bentuk [output].\nPastikan [kekangan]."),
             follow=[("Petua", "Tulis setiap unsur pada baris sendiri dengan label. Lebih mudah dibaca oleh AI dan oleh rakan sekerja.")],
             notes="Peserta boleh simpan templat ini dalam Bank Prompt."),
        dict(t="compare", kicker="CS5 &middot; Sebelum dan selepas", h="Prompt yang sama, hasil yang <em>berbeza</em>", menu="CS5: Sebelum dan selepas",
             bad=dict(label="Sebelum: prompt lemah", pre="Balas aduan jalan berlubang.", p="AI meneka lokasi, tarikh dan nada. Hasilnya umum dan mungkin berjanji perkara yang tidak dirancang."),
             good=dict(label="Selepas: lima unsur", pre="Peranan: Anda pegawai perhubungan awam JKR Daerah.\nKonteks: 6 lubang di Jalan Kg. Contoh selepas hujan. Kon telah dipasang; pembaikan 14-16 Okt.\nTugasan: Tulis balasan rasmi kepada pengadu.\nOutput: 3 perenggan pendek, sopan dan empati.\nKekangan: Jangan janji tarikh lain; jangan sebut nama pegawai.", p="Tepat, selamat dan sedia untuk disemak."),
             notes="Jalankan prompt lemah dahulu, kemudian prompt lima unsur dalam perbualan baharu."),
        dict(t="act", h="Sebelum dan selepas", min=10, menu="CS5: Aktiviti",
             steps=["Jalankan <code>Balas aduan jalan berlubang.</code>", "Buka <b>perbualan baharu</b>.", "Jalankan prompt lima unsur.", "Bandingkan kedua-dua output."],
             prompt=("CS5 &middot; Balasan aduan awam",
                     "Peranan: Anda pegawai perhubungan awam JKR Daerah.\nKonteks: Seorang penduduk mengadu melalui media sosial tentang 6 lubang di Jalan Kg. Contoh selepas hujan. Kon telah dipasang dan pembaikan dijadual 14-16 Okt.\nTugasan: Tulis balasan rasmi kepada pengadu.\nOutput: 3 perenggan pendek, nada sopan dan empati.\nKekangan: Jangan berjanji tarikh selain yang diberi; jangan sebut nama pegawai."),
             size="sm",
             follow=[("Versi pembantu tadbir", "Tukar Tugasan: <code>e-mel jemputan Mesyuarat Penyelarasan Bil. 3/2026 kepada 6 pegawai</code>"),
                     ("Versi pembantu kemahiran", "Tukar Tugasan: <code>laporan kerja harian daripada nota saya: [tampal nota]</code>")],
             notes="Minta dua peserta membacakan perbezaan yang paling ketara."),
        dict(t="cards", kicker="2.4 &middot; Teknik", h="Empat teknik untuk <em>kerja pejabat</em>", image="img/m2-11-prompt-berantai.jpg",
             image_alt="Aliran prompt berantai: nota, rangka, draf dan semakan.", image_fit="contain", image_caption="Prompt berantai: nota, rangka, draf, semakan. Ilustrasi AI.", cols=4,
             cards=[dict(lab="01", icon="text", h="Beri contoh", p="Tampal satu surat lama yang baik sebagai gaya rujukan, selepas membuang maklumat peribadi."),
                    dict(lab="02", icon="q", h="Minta AI bertanya dahulu", p="\"Sebelum menulis, tanya saya 5 soalan.\""),
                    dict(lab="03", icon="link", h="Prompt berantai", p="Pecahkan kerja besar: nota, rangka, draf, semakan."),
                    dict(lab="04", icon="repeat", h="Perhalusi", p="\"Pendekkan\", \"Lebih formal\", \"Jadikan jadual\", \"Terjemah ke Bahasa Inggeris\".")],
             notes="Teknik 3, prompt berantai, akan digunakan sepenuhnya dalam Hands-on 1 petang ini."),
        dict(t="points", kicker="Elakkan", h="Kesilapan <em>biasa</em>", image="img/m2-12-semakan-manusia.jpg",
             image_alt="Pegawai membandingkan draf AI dengan dokumen sumber sebelum menggunakannya.", style="warn",
             items=[("Prompt terlalu umum", "Tiada peranan, konteks atau format."),
                    ("Memasukkan data Merah", "IC, akaun bank, dokumen terperingkat."),
                    ("Menerima output tanpa semak", "Fakta, angka dan nama mesti disahkan."),
                    ("Satu perbualan untuk banyak tugas", "Mulakan perbualan baharu bagi tugas yang tidak berkaitan.")]),
        dict(t="act", h="Formula yang sama untuk <em>imej</em>", min=12, menu="CS6: Infografik",
             sub="Jana infografik, kemudian perhalusi dalam tiga pusingan. Semak setiap perkataan Melayu.",
             prompt=("CS6 &middot; Infografik zon kerja",
                     "Peranan: Anda pereka grafik untuk kempen keselamatan JKR.\nTugasan: Jana infografik menegak \"5 Langkah Selamat di Zon Kerja Jalan Raya\".\nKonteks: Untuk ditampal di papan notis pejabat dan dikongsi kepada pekerja tapak.\nOutput: 5 ikon bernombor dengan ayat pendek Bahasa Melayu, gaya rata, warna jingga dan kelabu.\nKekangan: Teks besar dan mudah dibaca; tiada logo."),
             size="sm",
             follow=[("Pusingan 2", "<code>Susun 5 langkah dalam bentuk anak panah dari atas ke bawah.</code>"),
                     ("Pusingan 3", "<code>Betulkan ejaan pada langkah [n] kepada \"[teks betul]\".</code>")],
             notes="AI imej masih kerap tersilap ejaan teks Melayu. Ini peluang mengamalkan semakan."),
        dict(t="points", kicker="CS6 &middot; Semak hasil imej", h="Menarik, tetapi <em>semak</em> dahulu", menu="CS6: Contoh hasil dan semakan",
             image="img/m2-13-contoh-infografik-zon-kerja.jpg", image_fit="poster",
             image_alt="Infografik AI lima langkah keselamatan zon kerja; contoh kesilapan: papan tanda mengandungi angka 140 yang tidak diminta.",
             image_caption="Contoh output AI untuk latihan semakan, bukan panduan keselamatan rasmi.",
             items=[("Semak teks dan susunan", "Lima langkah hadir. Baca setiap ayat dan semak ejaannya."),
                    ("Cari butiran yang tidak diminta", "Papan tanda memaparkan angka 140. Angka itu tidak diberi dalam prompt; minta AI membuangnya."),
                    ("Sahkan sebelum digunakan", "Semak ikon dan kesesuaian dengan arahan jabatan sebelum mengedar.")],
             notes="Tunjuk angka 140 pada langkah 3. Jangan tafsir sebagai had laju yang sah. Minta peserta mencadangkan prompt susulan untuk membuang angka itu, kemudian semak semula hasil. Contoh ini untuk latihan semakan output sahaja."),
        dict(t="flow", kicker="Senarai semak output", h="Sebelum guna, <em>semak</em> lima perkara",
             steps=[("01", "Tepat", "Fakta, angka, nama dan tarikh betul."), ("02", "Lengkap", "Semua yang diminta ada."),
                    ("03", "Nada", "Sesuai dengan penerima."), ("04", "Format", "Ikut templat jabatan."), ("05", "Selamat", "Tiada data Kuning atau Merah.")], on=[4],
             notes="Senarai semak ini juga digunakan dalam rubrik Hands-on 1."),
        dict(t="close", kicker="Rumusan Modul 2", h="Prompt yang baik ialah <em>arahan kerja</em> yang baik",
             items=[("5", "Lima unsur", "Peranan, Konteks, Tugasan, Output, Kekangan."),
                    ("4", "Empat teknik", "Contoh, tanya dahulu, berantai, perhalusi."),
                    ("1", "Satu formula", "Untuk teks, imej, video dan muzik.")],
             next=("Rehat 10.30. Seterusnya: <b>Modul 3, Komunikasi dan Dokumentasi</b> &middot; 11.00 pagi", "modul-3.html", "Slaid Modul 3")),
    ])

# ------------------------------------------------------------------ MODUL 3
M3 = dict(
    file="modul-3.html", label="Modul 3 &middot; Komunikasi &amp; Dokumentasi",
    title="Modul 3: AI untuk Komunikasi, Dokumentasi dan Mesyuarat",
    desc="Slaid Modul 3: surat rasmi, e-mel, laporan daripada gambar, slaid taklimat, video AI dan aliran minit mesyuarat.",
    slides=[
        dict(t="title", giant="03", eyebrow="Modul 3 &middot; Kursus Aplikasi AI dalam Tugas Rasmi",
             h="AI untuk Komunikasi, <em>Dokumentasi</em> dan Mesyuarat",
             sub="Satu kes tapak, enam hasil.", pills=["11.00 pagi-1.00 petang", "120 minit", PENCERAMAH]),
        dict(t="case", kicker="Senario sepanjang modul (rekaan)", h="Satu kes: <em>Jalan Kg. Contoh</em>", menu="Senario kes",
             facts=[("cone", "Kerosakan", "6 lubang dan bahu jalan runtuh selepas hujan lebat"),
                    ("map", "Lokasi", "Jalan Kg. Contoh, Rembau, KM 3.0 hingga 3.2"),
                    ("cal", "Kerja pembaikan", "14-16 Okt 2026, 8.00 pagi hingga 5.00 petang"),
                    ("route", "Laluan alternatif", "Melalui Jalan Sekolah")],
             notes="Semua butiran adalah rekaan. Kes yang sama digunakan untuk enam hasil supaya peserta nampak satu aliran kerja."),
        dict(t="agenda", kicker="Aliran modul", h="Satu kes, <em>enam</em> hasil",
             rows=[("11.00", "3A", "Surat rasmi", "30 minit"), ("11.30", "3B", "E-mel dan hebahan", "10 minit"),
                   ("11.40", "3C", "Laporan teknikal ringkas daripada gambar", "25 minit"), ("12.05", "3D", "Laporan kepada taklimat 5 slaid", "20 minit"),
                   ("12.25", "3E", "Video AI", "25 minit"), ("12.50", "3F", "Pengantar minit mesyuarat", "10 minit")]),
        dict(t="section", giant="3A", eyebrow="11.00 &middot; 30 minit", h="Surat <em>rasmi</em>", sub="Anatomi surat, templat jabatan dan prompt CS7."),
        dict(t="anatomy", kicker="Anatomi surat rasmi", h="Sembilan bahagian <em>surat</em>", menu="Anatomi surat rasmi",
             doc=[("1", "r", "Ruj. Kami: [ ]"), ("2", "r", "Tarikh: [ ]"), ("3", "", "Ketua Kampung, Kg. Contoh, Rembau"),
                  ("4", "", "Tuan,"), ("5", "", "<b>MAKLUMAN PENUTUPAN SEBAHAGIAN JALAN KG. CONTOH</b>"),
                  ("6", "bar", [100, 92, 96, 70]), ("", "bar", [100, 85]), ("7", "", "Sekian, terima kasih."),
                  ("8", "", "<b>\"MALAYSIA MADANI\"</b>"), ("9", "", "( [nama] ) Jurutera Daerah")],
             legend=[("1", "Rujukan"), ("2", "Tarikh"), ("3", "Alamat penerima"), ("4", "Salam"), ("5", "Perkara"),
                     ("6", "Isi bernombor"), ("7", "Penutup"), ("8", "Cogan kata"), ("9", "Tandatangan")],
             note="AI tidak tahu format terkini jabatan. Tampal templat kosong jabatan dan minta AI mengisi isi sahaja.",
             notes="Cogan kata dan format adalah contoh; ikut templat rasmi jabatan anda."),
        dict(t="act", h="Surat makluman penutupan jalan", min=15, menu="CS7: Surat rasmi",
             steps=["Tampal templat kosong jabatan pada baris akhir.", "Jalankan prompt.", "Semak setiap [ ] yang ditinggalkan AI."],
             prompt=("CS7 &middot; Surat rasmi",
                     "Peranan: Anda pembantu tadbir JKR Daerah Rembau yang mahir surat rasmi kerajaan.\nKonteks: Kerja membaiki 6 lubang dan bahu jalan di Jalan Kg. Contoh (KM 3.0 hingga 3.2) pada 14-16 Okt 2026, 8.00 pagi hingga 5.00 petang. Jalan ditutup sebelah; laluan alternatif melalui Jalan Sekolah.\nTugasan: Isi templat surat di bawah untuk memaklumkan Ketua Kampung dan memohon kerjasama menghebahkan kepada penduduk.\nOutput: Ikut templat sepenuhnya; isi bernombor; maksimum 1 halaman.\nKekangan: Jangan reka nombor rujukan, nama atau nombor telefon; tinggalkan [ ].\nTemplat:\n[tampal templat surat jabatan]"),
             size="xs",
             follow=[("Susulan 1", "<code>Tulis semula sebagai notis awam untuk papan tanda, nada mesra, 80 perkataan.</code>"),
                     ("Susulan 2", "<code>Terjemah surat ke Bahasa Inggeris rasmi.</code>")]),
        dict(t="email", kicker="3B &middot; E-mel dan hebahan", h="Baris pertama: <em>siapa, apa, bila</em>", menu="3B: E-mel",
             mail=dict(to="En. Rahman, Syarikat Contoh Sdn Bhd", subj="Pengesahan mula kerja Jalan Kg. Contoh, 14 Okt 2026",
                       first="Tuan, JKR Daerah Rembau ingin mengesahkan kerja pembaikan Jalan Kg. Contoh bermula 14 Okt 2026.",
                       body="Mohon jadual bekalan batu dikemukakan sebelum 10 Okt 2026 untuk tujuan perancangan..."),
             www=[("Siapa", "pengirim &amp; penerima"), ("Apa", "perkara utama"), ("Bila", "tarikh &amp; tempoh")],
             note="Penerima yang sibuk mungkin hanya membaca baris pertama.",
             notes="Tunjukkan bagaimana baris pertama sahaja sudah cukup untuk penerima bertindak."),
        dict(t="act", h="E-mel kontraktor dan mesej WhatsApp", min=8, menu="CS8: E-mel dan WhatsApp",
             prompt=("CS8 &middot; E-mel",
                     "Tulis e-mel susulan kepada kontraktor Syarikat Contoh Sdn Bhd untuk mengesahkan kerja bermula 14 Okt 2026 dan meminta jadual bekalan batu sebelum 10 Okt. Baris pertama mesti menyatakan siapa, apa dan bila. Nada profesional, maksimum 120 perkataan."),
             follow=[("Susulan", "<code>Ringkaskan maklumat penutupan jalan menjadi mesej WhatsApp 50 perkataan untuk kumpulan penduduk, dengan 1 emoji amaran.</code>")],
             steps=["Jalankan prompt e-mel.", "Semak baris pertama: siapa, apa, bila?", "Jalankan susulan WhatsApp."]),
        dict(t="section", giant="3C", eyebrow="11.40 &middot; 25 minit", h="Laporan daripada <em>gambar</em>", sub="Gemini boleh membaca gambar. Muat naik gambar sampel kerosakan bersama nota lapangan."),
        dict(t="flow", kicker="Struktur laporan pemeriksaan 1 halaman", h="Lima bahagian <em>laporan</em>", menu="Struktur laporan",
             steps=[("01", "Latar", "Lokasi, tarikh, sebab pemeriksaan."), ("02", "Pemerhatian", "Apa yang kelihatan, secara objektif."),
                    ("03", "Penilaian Awal", "Tafsiran pegawai."), ("04", "Cadangan Tindakan", "Kerja yang disyorkan."), ("05", "Lampiran", "Gambar dan lakaran.")], on=[2, 3],
             note="Kotak gelap: bahagian yang memerlukan pertimbangan kejuruteraan pegawai."),
        dict(t="act", h="Gambar kepada laporan pemeriksaan", min=15, menu="CS9: Laporan daripada gambar",
             steps=["Muat naik gambar sampel (disediakan).", "Tampal nota lapangan ringkas.", "Semak setiap [PERLU SAHKAN]."],
             prompt=("CS9 &middot; Teks + gambar",
                     "Peranan: Anda penolong jurutera JKR yang menulis laporan pemeriksaan jalan.\nKonteks: Gambar dilampirkan. Nota lapangan saya: [tampal nota ringkas].\nTugasan: (1) Huraikan apa yang kelihatan dalam gambar secara objektif. (2) Draf laporan pemeriksaan 1 halaman.\nOutput: Tajuk: Latar, Pemerhatian, Penilaian Awal, Cadangan Tindakan, Lampiran.\nKekangan: Tandakan [PERLU SAHKAN] pada setiap ukuran atau punca yang anda anggarkan; jangan reka angka."),
             size="sm"),
        dict(t="big", kicker="Peringatan", h="AI <em>menghurai</em> apa yang kelihatan.<br>Pegawai menilai.",
             sub="Penilaian kejuruteraan dan cadangan kerja tetap keputusan pegawai. Laporan teknikal penuh dibina dalam Modul 4 (Hari 2).",
             menu="AI menghurai, pegawai menilai"),
        dict(t="section", giant="3D", eyebrow="12.05 &middot; 20 minit", h="Laporan kepada <em>taklimat</em>", sub="Gunakan laporan daripada 3C dalam perbualan yang sama."),
        dict(t="act", h="Laporan kepada 5 slaid", min=12, menu="CS10: Taklimat 5 slaid",
             steps=["Kekal dalam perbualan 3C.", "Jalankan prompt.", "Jika Canvas tersedia, bina slaid dan eksport ke Google Slides."],
             prompt=("CS10 &middot; Slaid",
                     "Daripada laporan di atas, sediakan taklimat 5 slaid untuk Jurutera Daerah. Setiap slaid: tajuk, maksimum 3 poin, dan nota penceramah 2 ayat. Slaid terakhir ialah keputusan yang diminta daripada beliau."),
             follow=[("Jika Canvas tersedia", "<code>Bina slaid ini dalam Canvas.</code> kemudian eksport ke Google Slides."),
                     ("Hari 2", "Visualisasi didalami dalam Modul 5.")]),
        dict(t="section", giant="3E", eyebrow="12.25 &middot; 25 minit", h="Video <em>AI</em>", sub="Klip pendek dengan bunyi, daripada teks atau gambar."),
        dict(t="flow", kicker="Formula prompt video", h="Lima bahagian <em>babak</em>", menu="Formula video",
             steps=[("01", "Subjek", "Siapa atau apa?"), ("02", "Aksi", "Apa yang berlaku?"), ("03", "Latar", "Di mana, bila?"),
                    ("04", "Gaya kamera", "Pergerakan, sudut."), ("05", "Bunyi / dialog", "Latar bunyi dan suara.")],
             note="Kuota video harian terhad: satu cubaan sahaja setiap peserta."),
        dict(t="act", h="Video kempen 8 saat", min=10, menu="CS11: Video kempen",
             steps=["Satu cubaan sahaja setiap peserta.", "Kumpulan memilih klip terbaik.", "Untuk video lebih panjang, lihat demo Google Vids."],
             prompt=("CS11 &middot; Video",
                     "Video 8 saat, gaya dokumentari realistik: pekerja JKR berjaket pemantul cahaya meletakkan papan tanda \"JALAN DIBAIKI\" di jalan kampung Malaysia selepas hujan, kamera bergerak perlahan dari kiri ke kanan, waktu pagi berkabus. Bunyi: hujan renyai dan jentera jauh. Suara lelaki berkata: \"Maaf atas kesulitan, jalan anda sedang dibaiki.\""),
             notes="Kandungan AI untuk orang awam perlu dilabel mengikut amalan jabatan."),
        dict(t="flow", kicker="3F &middot; Pengantar minit mesyuarat", h="Lima langkah ke <em>minit</em>", menu="3F: Aliran minit mesyuarat",
             steps=[("01", "Bersihkan nota"), ("02", "Tanda jurang"), ("03", "Tetapkan format"), ("04", "Jana draf"), ("05", "Sahkan sebelum edar")], on=[1, 4],
             note="Bahan Hands-on 1 diedarkan sebelum rehat. Baca nota mesyuarat simulasi semasa makan tengah hari.",
             notes="Kotak gelap ialah langkah yang mesti dibuat oleh manusia."),
        dict(t="cards", kicker="Rumusan Modul 3", h="Satu kes, <em>enam</em> hasil", cols=3, menu="Rumusan: enam hasil",
             cards=[dict(lab="3A", icon="text", h="Surat rasmi", p="Isi templat jabatan."),
                    dict(lab="3B", icon="mail", h="E-mel + WhatsApp", p="Siapa, apa, bila."),
                    dict(lab="3C", icon="eye", h="Laporan pemeriksaan", p="Daripada gambar + nota."),
                    dict(lab="3D", icon="slides", h="Taklimat 5 slaid", p="Keputusan di slaid akhir."),
                    dict(lab="3E", icon="video", h="Video 8 saat", p="Satu cubaan, label kandungan."),
                    dict(lab="3F", icon="users", h="Minit mesyuarat", p="Hands-on 1 petang ini.", hl=True)]),
        dict(t="close", kicker="Sebelum rehat", h="Rehat dan makan <em>tengah hari</em>",
             items=[("1", "Baca nota", "Nota mesyuarat simulasi dalam bahan Hands-on 1."),
                    ("2", "Undi jingle", "Jingle CS4 dimainkan selepas rehat."),
                    ("3", "2.30 petang", "Duduk mengikut kumpulan.")],
             next=("Seterusnya: <b>Hands-on 1, Minit Mesyuarat</b> &middot; 2.30 petang", "hands-on.html", "Slaid Hands-on 1")),
    ])

# ------------------------------------------------------------------ HANDS-ON 1
NOTA = """Mesy penyelarasan kerja senggara jalan bil 3/2026
9 okt, bilik mesy JKR Daerah (rekaan)
hadir: JD (pengerusi), PJ Ali, PJ Siti, En Rahman (kontraktor), Pn Aina (PT, catat)
x hadir: wakil PBT
- PJ Ali: 6 lubang besar, bahu jln runtuh ~15m dekat km 3.2
- kontraktor kata boleh mula 14 okt, siap 3 hari. <mark>batu tunggu supplier</mark>
- PJ Siti: perlu notis kpd penduduk + ketua kg
- JD: notis keluar sebelum 12 okt. <mark class="r">siapa buat? (x putus)</mark>
- longkang tersumbat km 3.0, JD setuju <mark>tapi perlu semak peruntukan</mark>
- kontraktor tanya bayaran interim belum terima
- PT: tarikh mesy seterusnya <mark class="r">16 okt? atau 17 okt</mark>
- tamat 11.15 pg"""

H1 = dict(
    file="hands-on.html", label="Hands-on 1 &middot; Minit Mesyuarat",
    title="Hands-on 1: Bina Minit Mesyuarat menggunakan Prompt AI",
    desc="Slaid Hands-on 1: nota mesyuarat simulasi kepada minit lengkap, jadual tindakan, e-mel edaran, infografik dan Gem.",
    slides=[
        dict(t="title", giant="H1", eyebrow="Hands-on 1 &middot; Kursus Aplikasi AI dalam Tugas Rasmi",
             h="Bina <em>minit mesyuarat</em> menggunakan prompt AI",
             sub="Daripada nota bersepah kepada minit lengkap, jadual tindakan, e-mel edaran dan infografik.",
             pills=["2.30-4.30 petang", "120 minit", "Berkumpulan"]),
        dict(t="cards", kicker="Matlamat petang ini", h="Empat hasil dalam <em>90 minit</em>", cols=4,
             cards=[dict(icon="text", bigicon=True, h="Minit lengkap", p="Bahasa Melayu rasmi, ikut templat."),
                    dict(icon="list", bigicon=True, h="Jadual tindakan", p="Pegawai dan tarikh akhir."),
                    dict(icon="mail", bigicon=True, h="E-mel edaran", p="80 perkataan, 3 tindakan utama."),
                    dict(icon="gem", bigicon=True, h="Gem sendiri", p="Untuk diguna semula di pejabat.", hl=True)]),
        dict(t="cards", kicker="Peranan dalam kumpulan", h="Setiap orang ada <em>tugas</em>", cols=4,
             cards=[dict(lab="01", icon="pen", h="Setiausaha", p="Menaip prompt dan menyimpan hasil."),
                    dict(lab="02", icon="search", h="Penyemak Fakta", p="Membandingkan minit dengan nota asal."),
                    dict(lab="03", icon="hat", h="Penyemak Teknikal", p="Menyemak istilah teknikal dan tindakan."),
                    dict(lab="04", icon="slides", h="Pembentang", p="Membentang hasil dan satu jurang yang AI tidak tahu.")],
             notes="Beri 2 minit untuk kumpulan menentukan peranan."),
        dict(t="memo", kicker="Bahan: nota mesyuarat simulasi", h="Nota ini <em>sengaja</em> tidak tersusun", menu="Nota mesyuarat simulasi",
             memo=NOTA,
             side=[("alert", "Singkatan", "JD, PJ, PT, PBT, x, mesy, jln, kg."),
                   ("cal", "Tarikh bercanggah", "Mesyuarat seterusnya 16 atau 17 Okt?"),
                   ("user", "Tindakan tanpa pemilik", "Siapa menyediakan notis kepada penduduk?"),
                   ("shield", "Data rekaan", "Semua nama dan butiran adalah rekaan.")],
             notes="Versi penuh nota ada di laman Hands-on 1. Slaid ini memaparkan versi ringkas dengan bahagian bermasalah diserlahkan."),
        dict(t="agenda", kicker="Aliran kerja", h="Enam langkah, <em>prompt berantai</em>", menu="Enam langkah",
             rows=[("10 min", "1", "Bersihkan nota", "Prompt"), ("10 min", "2", "Tanda jurang, kumpulan putuskan", "Manusia"),
                   ("20 min", "3", "Jana minit ikut templat", "Prompt"), ("10 min", "4", "Jadual tindakan", "Prompt"),
                   ("15 min", "5", "Semakan kendiri + rubrik", "Manusia"), ("15 min", "6", "E-mel edaran + infografik", "Prompt")],
             notes="Setiap langkah dalam perbualan yang sama supaya AI mengingati konteks."),
        dict(t="act", badge="Langkah 1", h="Bersihkan nota", min=10, menu="Langkah 1: Bersihkan nota",
             steps=["Salin nota simulasi dari laman Hands-on 1.", "Tampal di tempat [tampal nota simulasi].", "Penyemak Fakta: pastikan tiada maklumat baharu."],
             prompt=("H1-1", "Anda setiausaha mesyuarat JKR. Nota di bawah ditulis cepat semasa mesyuarat. Kembangkan semua singkatan, betulkan ejaan, dan susun mengikut perkara yang dibincangkan. Jangan tambah apa-apa maklumat yang tiada dalam nota.\nNota:\n[tampal nota simulasi]")),
        dict(t="act", badge="Langkah 2", h="Tanda <em>jurang</em>", min=10, menu="Langkah 2: Tanda jurang",
             sub="Kumpulan, bukan AI, yang memutuskan jawapan bagi setiap jurang.",
             prompt=("H1-2", "Semak nota yang telah dibersihkan. Senaraikan dalam jadual: (a) maklumat yang bercanggah, (b) keputusan tanpa pegawai bertanggungjawab, (c) tindakan tanpa tarikh, (d) maklumat yang biasa ada dalam minit tetapi tiada di sini. Jangan isikan jawapan; saya akan putuskan."),
             follow=[("Kumpulan putuskan", "Tarikh mesyuarat seterusnya? Siapa menyediakan notis? Catat keputusan untuk Langkah 3.")]),
        dict(t="act", badge="Langkah 3", h="Jana minit ikut templat", min=20, menu="Langkah 3: Jana minit",
             steps=["Senaraikan keputusan kumpulan.", "Tampal templat minit (disediakan).", "Cari setiap [SEMAK] dalam hasil."],
             prompt=("H1-3", "Keputusan kumpulan bagi jurang tadi: [senaraikan]. Sekarang sediakan minit mesyuarat dalam Bahasa Melayu rasmi mengikut templat ini sepenuhnya: [tampal templat minit]. Gunakan ayat pasif rasmi (contoh: \"Mesyuarat bersetuju...\"). Tandakan [SEMAK] pada mana-mana fakta yang anda tidak pasti.")),
        dict(t="act", badge="Langkah 4", h="Jadual tindakan", min=10, menu="Langkah 4: Jadual tindakan",
             prompt=("H1-4", "Daripada minit tersebut, sediakan jadual tindakan: Bil., Perkara, Tindakan, Pegawai Bertanggungjawab, Tarikh Akhir. Susun mengikut tarikh akhir terdekat."),
             follow=[("Semak", "Setiap baris mesti ada pegawai dan tarikh. Baris kosong bermakna jurang belum diselesaikan.")]),
        dict(t="act", badge="Langkah 5", h="Semakan <em>kendiri</em>", min=15, menu="Langkah 5: Semakan kendiri",
             steps=["Jalankan prompt semakan.", "Penyemak Fakta dan Penyemak Teknikal menilai dengan rubrik.", "Betulkan minit sebelum Langkah 6."],
             prompt=("H1-5", "Bandingkan minit akhir dengan nota asal ayat demi ayat. Senaraikan apa-apa ayat dalam minit yang tidak disokong oleh nota asal.")),
        dict(t="act", badge="Langkah 6", h="E-mel edaran dan <em>infografik</em>", min=15, menu="Langkah 6: E-mel dan infografik",
             prompt=[("H1-6 &middot; E-mel", "Tulis e-mel edaran minit kepada semua yang hadir, 80 perkataan, sebut 3 tindakan utama dan tarikh mesyuarat seterusnya."),
                     ("H1-6 &middot; Imej", "Jana infografik satu halaman \"Keputusan Mesyuarat Bil. 3/2026\": 4 keputusan utama dengan ikon, gaya rata, warna biru JKR. Teks Bahasa Melayu besar dan jelas.")],
             size="sm", steps=["Jalankan prompt e-mel.", "Jalankan prompt infografik.", "Semak ejaan pada infografik."]),
        dict(t="table", kicker="Rubrik semakan minit", h="Markah 0 hingga 2, maksimum <em>12</em>", menu="Rubrik semakan",
             head=["Kriteria", "2", "1", "0"],
             rows=[["Ketepatan fakta", "Semua fakta sepadan dengan nota", "1 kesilapan kecil", "Ada fakta rekaan AI"],
                   ["Jurang diselesaikan", "Tarikh bercanggah dan tindakan tanpa pemilik diputuskan kumpulan", "Satu diselesaikan", "Dibiarkan atau diisi AI"],
                   ["Format", "Ikut templat jabatan sepenuhnya", "Sebahagian", "Tidak ikut"],
                   ["Jadual tindakan", "Setiap tindakan ada pegawai dan tarikh", "Sebahagian", "Tiada"],
                   ["Bahasa", "Bahasa Melayu rasmi, ringkas", "Ada bahasa pasar", "Tidak sesuai"],
                   ["Keselamatan data", "Hanya data rekaan", "&ndash;", "Data sebenar dimasukkan"]]),
        dict(t="cards", kicker="Pembentangan kumpulan", h="Tiga minit, <em>tiga</em> perkara", cols=3,
             cards=[dict(lab="01", icon="text", h="Tunjuk hasil", p="Minit dan jadual tindakan akhir."),
                    dict(lab="02", icon="alert", h="Satu jurang", p="Perkara yang AI tidak tahu dan bagaimana kumpulan memutuskannya."),
                    dict(lab="03", icon="target", h="Markah rubrik", p="Markah kendiri dan satu penambahbaikan.", hl=True)]),
        dict(t="act", badge="Penutup", h="Bina <em>Gem</em> anda sendiri", menu="Bina Gem sendiri",
             sub="Gem ialah pembantu Gemini yang menyimpan arahan tetap. Esok di pejabat, anda hanya perlu menampal nota.",
             steps=["Dalam Gemini, pilih <b>Gems</b>.", "Pilih <b>Gem baharu</b>.", "Tampal arahan, lampirkan templat minit, simpan."],
             prompt=("Gem &middot; Setiausaha Mesyuarat JKR", "Anda setiausaha mesyuarat JKR Daerah. Apabila saya tampal nota mesyuarat: (1) bersihkan dan susun mengikut perkara; (2) senaraikan jurang dan tunggu jawapan saya; (3) jana minit dalam Bahasa Melayu rasmi mengikut templat yang dilampirkan; (4) sediakan jadual tindakan. Jangan sekali-kali mereka fakta, nama atau tarikh. Ingatkan saya untuk membuang maklumat sulit sebelum menampal.")),
        dict(t="close", kicker="Refleksi", h="Satu tugas, satu prompt, <em>minggu depan</em>",
             items=[("1", "Tugas", "Tulis satu tugas berulang yang akan anda cuba dengan AI."),
                    ("2", "Prompt", "Tulis prompt pertama menggunakan lima unsur."),
                    ("3", "Semak", "Siapa yang akan menyemak hasilnya sebelum diguna?")],
             next=("Hari 2 (8 Okt): <b>Modul 4 dan 5</b> bersama PM Ts Dr Mohd Shahizan Othman", "../slaid.html", "Semua slaid"),
             notes="Terima kasih. Ingatkan peserta tentang Hari 2 dan Pasca-Ujian."),
    ])

DECKS = [M1, M2, M3, H1]
